export const defaultGraphData = {
  nodes: [
    { id: "ai", type: "Concept", label: "Artificial Intelligence" },
    { id: "data_analytics", type: "Concept", label: "Data Analytics" },
    { id: "machine_learning", type: "Method", label: "Machine Learning" },
    { id: "deep_learning", type: "Method", label: "Deep Learning" },
    { id: "nlp", type: "Method", label: "Natural Language Processing" },
    { id: "predictive_analytics", type: "Concept", label: "Predictive Analytics" },
    { id: "prescriptive_analytics", type: "Concept", label: "Prescriptive Analytics" },
    { id: "augmented_analytics", type: "Concept", label: "Augmented Analytics" },
    { id: "xai", type: "Concept", label: "Explainable AI (XAI)" },
    { id: "algorithmic_bias", type: "ResearchGap", label: "Algorithmic Bias and Fairness" },
    { id: "black_box_problem", type: "ResearchGap", label: "Lack of Explainability" },
    { id: "skill_gaps", type: "ResearchGap", label: "Technical Complexity and Skill Gaps" },
    { id: "data_quality_issue", type: "ResearchGap", label: "Data Quality and Availability" },
    { id: "automation", type: "Finding", label: "Automation of Complex Data Tasks" },
    { id: "enhanced_accuracy", type: "Finding", label: "Enhanced Accuracy and Precision" },
    { id: "real_time_processing", type: "Finding", label: "Real-Time Data Processing" },
    { id: "scalability", type: "Metric", label: "Scalability" },
    { id: "ibm_watson", type: "Technology", label: "IBM Watson" },
    { id: "fico_falcon", type: "Technology", label: "FICO Falcon" },
    { id: "thematic_analysis", type: "Method", label: "Thematic Analysis" },
    { id: "edge_computing", type: "Technology", label: "Edge Computing" },
    { id: "decision_intelligence", type: "Concept", label: "Decision Intelligence" }
  ],
  relationships: [
    { source: "ai", target: "data_analytics", type: "IMPROVES" },
    { source: "ai", target: "machine_learning", type: "USES" },
    { source: "ai", target: "deep_learning", type: "USES" },
    { source: "ai", target: "nlp", type: "USES" },
    { source: "ai", target: "automation", type: "ACHIEVES" },
    { source: "ai", target: "predictive_analytics", type: "IMPROVES" },
    { source: "ai", target: "real_time_processing", type: "ACHIEVES" },
    { source: "machine_learning", target: "enhanced_accuracy", type: "ACHIEVES" },
    { source: "ai", target: "prescriptive_analytics", type: "IMPROVES" },
    { source: "ai", target: "scalability", type: "IMPROVES" },
    { source: "augmented_analytics", target: "ai", type: "USES" },
    { source: "augmented_analytics", target: "machine_learning", type: "USES" },
    { source: "black_box_problem", target: "ai", type: "IDENTIFIES_GAP" },
    { source: "algorithmic_bias", target: "ai", type: "IDENTIFIES_GAP" },
    { source: "xai", target: "ai", type: "IMPROVES" },
    { source: "ibm_watson", target: "ai", type: "BASED_ON" },
    { source: "fico_falcon", target: "ai", type: "BASED_ON" },
    { source: "edge_computing", target: "real_time_processing", type: "IMPROVES" },
    { source: "ai", target: "decision_intelligence", type: "ENABLES" },
    { source: "data_analytics", target: "thematic_analysis", type: "EVALUATED_WITH" },
    { source: "data_quality_issue", target: "ai", type: "IDENTIFIES_GAP" },
    { source: "skill_gaps", target: "ai", type: "IDENTIFIES_GAP" }
  ]
};
