import './global.css';
import '@app-ui/src/styles/global.css'
export const metadata = {
  title: 'Welcome to ArtiEaz',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
